spring:
  application:
    name: event
  threads:
    virtual:
      enabled: true
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:2222/event_db
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
logging:
    level:
      org.example.security: INFO
      org.springframework.security: DEBUG
server:
    port: 2223